import { Router } from '@angular/router';
import { ButtonDefinition } from '../shared/models/base.model';
import { AggregatorService } from '../shared/services/aggregator.service';
export declare class DefaultLayoutService {
    private router;
    private _aggregatorService;
    navType: string;
    themeLayout: string;
    layoutType: string;
    verticalPlacement: string;
    verticalLayout: string;
    deviceType: string;
    imgSrc: string;
    imgTitle: string;
    verticalNavType: string;
    verticalEffect: string;
    vNavigationView: string;
    pcodedHeaderPosition: string;
    pcodedSidebarPosition: string;
    headerTheme: string;
    logoTheme: string;
    innerHeight: string;
    windowWidth: number;
    toggleOn: boolean;
    headerFixedMargin: string;
    navBarTheme: string;
    activeItemTheme: string;
    isCollapsedMobile: string;
    chatToggle: string;
    chatToggleInverse: string;
    chatInnerToggle: string;
    chatInnerToggleInverse: string;
    menuTitleTheme: string;
    itemBorder: boolean;
    itemBorderStyle: string;
    subItemBorder: boolean;
    subItemIcon: string;
    dropDownIcon: string;
    isSidebarChecked: boolean;
    isHeaderChecked: boolean;
    private subscriptions;
    private toolbarItems;
    constructor(router: Router, _aggregatorService: AggregatorService);
    ngOnDestroy(): void;
    onResize(event: any): void;
    setMenuAttributes(windowWidth: any): void;
    toggleOpened(): void;
    onClickedOutside(e: Event): void;
    onMobileMenu(): void;
    toggleChat(): void;
    toggleChatInner(): void;
    setSidebarPosition(): void;
    setHeaderPosition(): void;
    setBackgroundPattern(pattern: any): void;
    setLayoutType(type: string): void;
    setNavBarTheme(theme: string): void;
    initToolbarItems(actions: string[]): void;
    getToolbarItems(): ButtonDefinition[];
    hasToolbarItems(): boolean;
    showImage(image: any): void;
}
